
INSERT INTO Trivia (CategoriaId, Titulo, Descripcion, Dificultad, PuntosMaximos, Estado) VALUES
(1, N'¿El papel se puede reciclar?', N'Sí, se puede reciclar.', N'Facil', 10, 'ACTIVA'),
(1, N'¿El cartón se puede reciclar?', N'Sí, se puede reciclar.', N'Facil', 10, 'ACTIVA'),
(1, N'¿El vidrio se puede reciclar?', N'Sí, se puede reciclar.', N'Facil', 10, 'ACTIVA'),
(1, N'¿El aluminio se puede reciclar?', N'Sí, se puede reciclar.', N'Facil', 10, 'ACTIVA'),
(1, N'¿El acero se puede reciclar?', N'Sí, se puede reciclar.', N'Facil', 10, 'ACTIVA'),
(1, N'¿Las botellas de plástico PET se puede reciclar?', N'Sí, se puede reciclar.', N'Facil', 10, 'ACTIVA'),
(1, N'¿El tetra pak se puede reciclar?', N'Sí, se puede reciclar.', N'Facil', 10, 'ACTIVA'),
(1, N'¿La chatarra metálica se puede reciclar?', N'Sí, se puede reciclar.', N'Facil', 10, 'ACTIVA'),
(1, N'¿Las revistas viejas se puede reciclar?', N'Sí, se puede reciclar.', N'Facil', 10, 'ACTIVA'),
(1, N'¿El periódico se puede reciclar?', N'Sí, se puede reciclar.', N'Facil', 10, 'ACTIVA'),
(1, N'¿Las latas de gaseosa se puede reciclar?', N'Sí, se puede reciclar.', N'Facil', 10, 'ACTIVA'),
(1, N'¿Las cajas de cereal se puede reciclar?', N'Sí, se puede reciclar.', N'Facil', 10, 'ACTIVA'),
(1, N'¿Los frascos de vidrio se puede reciclar?', N'Sí, se puede reciclar.', N'Facil', 10, 'ACTIVA'),
(1, N'¿El papel de oficina se puede reciclar?', N'Sí, se puede reciclar.', N'Facil', 10, 'ACTIVA'),
(1, N'¿El papel higiénico usado se puede depositar en el contenedor de reciclaje común?', N'No, debe ir a la basura común o a un punto especial.', N'Facil', 10, 'ACTIVA'),
(1, N'¿Los pañales desechables se puede depositar en el contenedor de reciclaje común?', N'No, debe ir a la basura común o a un punto especial.', N'Facil', 10, 'ACTIVA'),
(1, N'¿Las colillas de cigarro se puede depositar en el contenedor de reciclaje común?', N'No, debe ir a la basura común o a un punto especial.', N'Facil', 10, 'ACTIVA'),
(1, N'¿El poliestireno expandido (icopor) se puede depositar en el contenedor de reciclaje común?', N'No, debe ir a la basura común o a un punto especial.', N'Facil', 10, 'ACTIVA'),
(1, N'¿El papel carbón se puede depositar en el contenedor de reciclaje común?', N'No, debe ir a la basura común o a un punto especial.', N'Facil', 10, 'ACTIVA'),
(1, N'¿El papel plastificado se puede depositar en el contenedor de reciclaje común?', N'No, debe ir a la basura común o a un punto especial.', N'Facil', 10, 'ACTIVA'),
(1, N'¿El chicle se puede depositar en el contenedor de reciclaje común?', N'No, debe ir a la basura común o a un punto especial.', N'Facil', 10, 'ACTIVA'),
(1, N'¿La cerámica rota se puede depositar en el contenedor de reciclaje común?', N'No, debe ir a la basura común o a un punto especial.', N'Facil', 10, 'ACTIVA'),
(1, N'¿Los espejos rotos se puede depositar en el contenedor de reciclaje común?', N'No, debe ir a la basura común o a un punto especial.', N'Facil', 10, 'ACTIVA'),
(1, N'¿Los CD y DVD se puede depositar en el contenedor de reciclaje común?', N'No, debe ir a la basura común o a un punto especial.', N'Facil', 10, 'ACTIVA'),
(1, N'¿Las servilletas usadas con comida se puede depositar en el contenedor de reciclaje común?', N'No, debe ir a la basura común o a un punto especial.', N'Facil', 10, 'ACTIVA'),
(1, N'¿El papel aluminio con grasa se puede depositar en el contenedor de reciclaje común?', N'No, debe ir a la basura común o a un punto especial.', N'Facil', 10, 'ACTIVA'),
(1, N'¿De qué color suele ser el contenedor destinado al papel y cartón?', N'Azul.', N'Facil', 10, 'ACTIVA'),
(1, N'¿De qué color suele ser el contenedor destinado al vidrio?', N'Verde.', N'Facil', 10, 'ACTIVA'),
(1, N'¿De qué color suele ser el contenedor destinado a envases plásticos y latas?', N'Amarillo.', N'Facil', 10, 'ACTIVA'),
(1, N'¿Qué se debe hacer con una botella de plástico antes de reciclarla?', N'Vaciarla y enjuagarla.', N'Facil', 10, 'ACTIVA'),
(1, N'¿Se debe reciclar el cartón de pizza con restos de grasa y comida?', N'No, la grasa impide su reciclaje.', N'Facil', 10, 'ACTIVA'),
(1, N'¿Qué material se obtiene al reciclar botellas de vidrio?', N'Vidrio nuevo.', N'Facil', 10, 'ACTIVA'),
(1, N'¿Es buena práctica separar la basura orgánica de la reciclable?', N'Sí, facilita el proceso de reciclaje.', N'Facil', 10, 'ACTIVA'),
(1, N'¿Se puede reciclar una lata de aluminio infinitas veces?', N'Sí, el aluminio se puede reciclar casi infinitamente.', N'Facil', 10, 'ACTIVA'),
(1, N'¿Qué es el reciclaje?', N'El proceso de convertir residuos en nuevos materiales o productos.', N'Facil', 10, 'ACTIVA'),
(1, N'¿Ayuda el reciclaje a reducir la basura en los rellenos sanitarios?', N'Sí, reduce la cantidad de basura enviada a rellenos.', N'Facil', 10, 'ACTIVA'),
(1, N'¿Qué material tarda más en descomponerse: una botella de vidrio o una cáscara de banano?', N'La botella de vidrio.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Cuál tarda más en degradarse: una bolsa plástica o una hoja de papel?', N'La bolsa plástica.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Qué significa la sigla PET en los envases plásticos?', N'Tereftalato de polietileno.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Qué es la economía del reciclaje conocida como ''las 3R''?', N'Reducir, Reutilizar y Reciclar.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Por qué es importante separar los residuos desde el hogar?', N'Porque facilita y hace más eficiente el proceso de reciclaje.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Qué ocurre si se mezclan residuos reciclables con residuos orgánicos?', N'Se pueden contaminar y volverse no reciclables.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Qué es un punto limpio o centro de acopio?', N'Un lugar destinado a recibir y clasificar materiales reciclables.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Las pilas y baterías se deben desechar en la basura común?', N'No, requieren un punto de recolección especial.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Qué material reciclado se usa comúnmente para fabricar ropa polar (fleece)?', N'El plástico PET reciclado.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Qué es el ''upcycling'' o suprarreciclaje?', N'Transformar un residuo en un producto de mayor valor sin destruir el material.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Los aceites de cocina usados se pueden verter por el desagüe?', N'No, deben llevarse a un punto de recolección especial.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Qué porcentaje aproximado de la basura doméstica es potencialmente reciclable?', N'Alrededor de la mitad, dependiendo del hogar.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Qué pasa con el papel al reciclarse varias veces?', N'Sus fibras se acortan y pierde calidad progresivamente.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Qué es la ''contaminación cruzada'' en el reciclaje?', N'Cuando materiales no reciclables ensucian o mezclan los reciclables.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Qué residuo electrónico requiere manejo especial por sus componentes tóxicos?', N'Los celulares y computadoras en desuso (e-waste).', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Reciclar aluminio consume menos energía que producirlo desde cero?', N'Sí, consume mucha menos energía.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Qué se recomienda hacer con las cajas de cartón antes de reciclarlas?', N'Aplanarlas para ahorrar espacio.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿El icopor (poliestireno expandido) es fácil de reciclar?', N'No, es difícil y poco rentable de reciclar.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Qué es la logística inversa en el reciclaje?', N'El proceso de devolver productos usados a la cadena para su reciclaje.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Los envases con restos de pintura o químicos se reciclan igual que los limpios?', N'No, requieren manejo especial como residuo peligroso.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Qué es el compostaje?', N'El proceso de descomponer residuos orgánicos para producir abono.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Qué material se produce al reciclar llantas usadas?', N'Caucho triturado para pisos o asfalto.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Cuál es una ventaja ambiental clave del reciclaje de papel?', N'Reduce la tala de árboles.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Qué hacer con la ropa vieja en buen estado en vez de botarla?', N'Donarla o reutilizarla.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Qué código numérico identifica al plástico PET en el sistema de clasificación de plásticos?', N'El número 1.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué código numérico identifica al plástico HDPE (polietileno de alta densidad)?', N'El número 2.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Cuántas veces se estima que se puede reciclar el papel antes de que sus fibras dejen de ser útiles?', N'Entre 5 y 7 veces aproximadamente.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué proceso permite separar metales ferrosos de los residuos mediante imanes?', N'La separación magnética.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué nombre recibe la tecnología que separa materiales reciclables por su composición usando luz infrarroja?', N'Separación óptica (NIR).', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué es la ''responsabilidad extendida del productor'' (REP)?', N'Un principio que obliga a los fabricantes a gestionar el ciclo de vida final de sus productos.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué material reciclado se usa para fabricar el pavimento asfáltico modificado con caucho?', N'El caucho de llantas recicladas.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué diferencia hay entre reciclaje mecánico y reciclaje químico del plástico?', N'El mecánico solo transforma la forma del material; el químico rompe sus moléculas para crear nueva materia prima.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué porcentaje del plástico producido a nivel mundial se estima que ha sido reciclado alguna vez?', N'Menos del 10%.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué es el ''downcycling''?', N'Reciclar un material convirtiéndolo en un producto de menor calidad o valor.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué es la pirólisis aplicada al reciclaje de plásticos?', N'Un proceso térmico que descompone el plástico en combustibles o materias primas.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué gas de efecto invernadero se reduce significativamente al reciclar aluminio en vez de producirlo desde bauxita?', N'El dióxido de carbono (CO2).', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué es un vertedero sanitario o relleno sanitario controlado?', N'Una instalación diseñada para disponer residuos minimizando el impacto ambiental.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué contaminante se genera comúnmente por la incineración de plásticos sin control?', N'Dioxinas y furanos.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué se entiende por economía circular en relación al reciclaje?', N'Un modelo que busca mantener los materiales en uso el mayor tiempo posible, minimizando residuos.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué es el ''lixiviado'' en un relleno sanitario?', N'Un líquido contaminante generado por la descomposición de los residuos.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué material reciclado se usa para producir fibra textil reciclada conocida como ''rPET''?', N'Botellas de plástico PET recicladas.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué organismo internacional impulsa el Convenio de Basilea sobre residuos peligrosos?', N'Naciones Unidas (PNUMA).', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué diferencia existe entre biodegradable y compostable?', N'Lo compostable se descompone en condiciones controladas en un tiempo definido, sin dejar residuos tóxicos.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué es el ''greenwashing'' aplicado al reciclaje?', N'Presentar un producto o empresa como más sostenible de lo que realmente es.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué material se recupera principalmente de las tarjetas madre electrónicas?', N'Metales preciosos como oro y cobre.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué significa la sigla RAEE?', N'Residuos de Aparatos Eléctricos y Electrónicos.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué proceso separa los residuos por densidad usando corrientes de aire?', N'Separación aerodinámica o por corrientes de aire.', N'Dificil', 35, 'ACTIVA'),
(2, N'¿Caminar es una forma de movilidad sostenible?', N'Sí, no genera emisiones.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Andar en bicicleta contamina el aire?', N'No, la bicicleta no genera emisiones.', N'Facil', 10, 'ACTIVA'),
(2, N'¿El transporte público reduce la cantidad de autos en la calle?', N'Sí, al transportar a más personas en un solo vehículo.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Un auto eléctrico emite gases por el tubo de escape?', N'No, no tiene tubo de escape ni emisiones directas.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Compartir el auto con otras personas (carpool) ayuda al ambiente?', N'Sí, reduce el número de vehículos circulando.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Usar más la bicicleta ayuda a reducir el tráfico?', N'Sí, reduce la congestión vehicular.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Qué vehículo contamina más: uno eléctrico o uno de gasolina?', N'El de gasolina.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Caminar distancias cortas en vez de usar el auto reduce emisiones?', N'Sí, definitivamente.', N'Facil', 10, 'ACTIVA'),
(2, N'¿El scooter eléctrico es una alternativa de movilidad sostenible?', N'Sí, es una alternativa de bajas emisiones.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Mantener las llantas del auto infladas correctamente ahorra combustible?', N'Sí, reduce el consumo de combustible.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Usar el transporte público en vez del auto propio reduce la huella de carbono?', N'Sí, la reduce considerablemente.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Es sostenible usar el auto para trayectos que se pueden caminar en 5 minutos?', N'No, sería más sostenible caminar.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Qué se entiende por ''movilidad activa''?', N'Desplazarse usando el propio esfuerzo físico, como caminar o pedalear.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Qué ventaja ambiental tiene el transporte ferroviario frente al transporte por carretera?', N'Emite menos gases de efecto invernadero por pasajero transportado.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Qué es un carril bici o ciclovía?', N'Una vía exclusiva destinada a la circulación segura de bicicletas.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Qué es el ''car sharing''?', N'Un sistema de vehículos compartidos entre varios usuarios.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Qué beneficio tiene electrificar el transporte público de una ciudad?', N'Reduce las emisiones contaminantes y el ruido urbano.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Qué significa ''huella de carbono'' en el contexto de movilidad?', N'La cantidad de gases de efecto invernadero emitidos por un medio de transporte.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Qué es una ''supermanzana'' urbana?', N'Un área urbana que prioriza al peatón y limita el paso de vehículos motorizados.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Por qué los autos eléctricos se consideran más eficientes energéticamente?', N'Porque convierten mayor porcentaje de la energía en movimiento, con menos pérdidas.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Qué es la intermodalidad en el transporte?', N'Combinar distintos medios de transporte en un mismo trayecto de forma articulada.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Qué impacto tiene la congestión vehicular sobre las emisiones?', N'Las aumenta, ya que los motores consumen más combustible en marcha lenta.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Qué es un vehículo híbrido?', N'Un vehículo que combina un motor de combustión con un motor eléctrico.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Qué rol cumplen las estaciones de carga eléctrica en la movilidad sostenible?', N'Permiten recargar vehículos eléctricos y fomentan su uso.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Qué es el peaje urbano o ''congestion charge''?', N'Un cobro por circular en auto en zonas céntricas para reducir el tráfico.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Qué beneficio para la salud tiene fomentar la movilidad activa?', N'Mejora la condición física y reduce enfermedades sedentarias.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Qué es la micromovilidad?', N'El uso de vehículos ligeros como bicicletas y patinetes eléctricos para trayectos cortos.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Qué gas es el principal responsable del efecto invernadero emitido por los autos a combustión?', N'El dióxido de carbono (CO2).', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Qué es un sistema BRT (Bus Rapid Transit)?', N'Un sistema de autobuses de tránsito rápido con carriles exclusivos.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Qué ventaja tiene teletrabajar en relación a la movilidad sostenible?', N'Reduce la necesidad de desplazamientos diarios y sus emisiones.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Qué indicador mide las emisiones de CO2 por pasajero-kilómetro transportado?', N'La intensidad de carbono del transporte.', N'Dificil', 35, 'ACTIVA'),
(2, N'¿Qué es el efecto ''rebote'' en eficiencia vehicular?', N'Cuando la mejora en eficiencia genera más uso del vehículo, anulando parte del ahorro energético.', N'Dificil', 35, 'ACTIVA'),
(2, N'¿Qué tecnología permite a los trenes recuperar energía al frenar?', N'El frenado regenerativo.', N'Dificil', 35, 'ACTIVA'),
(2, N'¿Qué es el análisis de ciclo de vida aplicado a un vehículo eléctrico?', N'Una evaluación del impacto ambiental desde su fabricación hasta su desecho.', N'Dificil', 35, 'ACTIVA'),
(2, N'¿Qué mineral crítico es clave para fabricar baterías de vehículos eléctricos?', N'El litio.', N'Dificil', 35, 'ACTIVA'),
(2, N'¿Qué es la ''curva de Kuznets ambiental'' aplicada al transporte?', N'Una teoría que relaciona el desarrollo económico con el impacto ambiental, incluyendo la motorización.', N'Dificil', 35, 'ACTIVA'),
(2, N'¿Qué significa el término ''última milla'' en logística de transporte?', N'El tramo final de entrega de un producto o de un trayecto de transporte público.', N'Dificil', 35, 'ACTIVA'),
(2, N'¿Qué es el hidrógeno verde aplicado a la movilidad?', N'Hidrógeno producido con energías renovables, usado como combustible limpio en vehículos.', N'Dificil', 35, 'ACTIVA'),
(2, N'¿Qué es la electromovilidad?', N'El uso de vehículos que funcionan total o parcialmente con energía eléctrica.', N'Dificil', 35, 'ACTIVA'),
(2, N'¿Qué diferencia hay entre un vehículo híbrido enchufable (PHEV) y uno híbrido convencional (HEV)?', N'El PHEV puede cargarse desde una toma eléctrica externa; el HEV no.', N'Dificil', 35, 'ACTIVA'),
(2, N'¿Qué es el urbanismo orientado al tránsito (TOD)?', N'Un modelo de planificación urbana centrado en el transporte público y la movilidad no motorizada.', N'Dificil', 35, 'ACTIVA'),
(2, N'¿Qué compuesto contaminante emitido por vehículos diésel afecta gravemente la calidad del aire urbano?', N'Óxidos de nitrógeno (NOx) y material particulado.', N'Dificil', 35, 'ACTIVA'),
(2, N'¿Qué mide el índice de motorización de una ciudad?', N'La cantidad de vehículos por cada mil habitantes.', N'Dificil', 35, 'ACTIVA'),
(2, N'¿Qué es la ''ciudad de los 15 minutos''?', N'Un modelo urbano donde los servicios esenciales están a 15 minutos a pie o en bici.', N'Dificil', 35, 'ACTIVA'),
(3, N'¿Los árboles producen oxígeno?', N'Sí, mediante la fotosíntesis.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Reforestar significa sembrar árboles en zonas donde antes había bosque?', N'Sí, así es.', N'Facil', 10, 'ACTIVA'),
(3, N'¿La biodiversidad se refiere a la variedad de seres vivos en un lugar?', N'Sí, exactamente.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Los bosques ayudan a evitar la erosión del suelo?', N'Sí, sus raíces sostienen la tierra.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Cortar árboles sin control se llama deforestación?', N'Sí, correcto.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Las abejas ayudan a polinizar las plantas?', N'Sí, son polinizadores clave.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Los bosques absorben dióxido de carbono?', N'Sí, actúan como sumideros de carbono.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Es importante proteger a los animales en peligro de extinción?', N'Sí, para conservar la biodiversidad.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Sembrar un árbol nativo es mejor que uno de especie no nativa para el ecosistema local?', N'Sí, generalmente es más beneficioso.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Los humedales son ecosistemas importantes para la biodiversidad?', N'Sí, albergan gran variedad de especies.', N'Facil', 10, 'ACTIVA'),
(3, N'¿La tala ilegal afecta negativamente a los bosques?', N'Sí, los degrada y reduce su biodiversidad.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Los árboles ayudan a regular la temperatura del ambiente?', N'Sí, brindan sombra y regulan el microclima.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Qué es un ecosistema?', N'Una comunidad de seres vivos que interactúan entre sí y con su entorno físico.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Qué es una especie endémica?', N'Una especie que solo existe naturalmente en una región geográfica determinada.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Qué función cumplen los corredores biológicos?', N'Conectar ecosistemas fragmentados para permitir el movimiento de especies.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Qué es la deforestación?', N'La eliminación o tala masiva de bosques, generalmente para otros usos de suelo.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Por qué es preferible reforestar con especies nativas?', N'Porque se adaptan mejor al ecosistema local y benefician a la fauna nativa.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Qué es la fragmentación de hábitats?', N'La división de un ecosistema en parches aislados por actividad humana.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Qué es una especie en peligro de extinción?', N'Una especie cuya población ha disminuido al punto de riesgo de desaparecer.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Qué es un sumidero de carbono?', N'Un sistema natural que absorbe más carbono del que libera, como un bosque.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Qué papel cumplen los polinizadores en la biodiversidad?', N'Permiten la reproducción de muchas plantas al transportar el polen.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Qué es un área protegida?', N'Un espacio delimitado para la conservación de la naturaleza y sus especies.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Qué es la reforestación urbana?', N'La siembra de árboles dentro de las ciudades para mejorar el ambiente urbano.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Qué consecuencia tiene la pérdida de bosques sobre el ciclo del agua?', N'Reduce la capacidad de retención e infiltración de agua en el suelo.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Qué es un ecosistema de manglar?', N'Un ecosistema costero de árboles adaptados a agua salobre, clave para la biodiversidad marina.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Qué es la restauración ecológica?', N'El proceso de ayudar a recuperar un ecosistema degradado o destruido.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Qué relación existe entre biodiversidad y resiliencia de un ecosistema?', N'A mayor biodiversidad, mayor capacidad del ecosistema para resistir y recuperarse de alteraciones.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Qué es la caza furtiva?', N'La caza ilegal de especies, muchas veces protegidas o en peligro.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Qué es un banco de semillas?', N'Un lugar donde se conservan semillas para preservar la diversidad genética de plantas.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Qué diferencia hay entre reforestación y forestación?', N'La reforestación siembra donde antes hubo bosque; la forestación siembra donde nunca lo hubo.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Qué es la ''deuda de extinción'' en ecología?', N'El número de especies que eventualmente se extinguirán debido a perturbaciones pasadas del hábitat.', N'Dificil', 35, 'ACTIVA'),
(3, N'¿Qué es una especie clave o ''keystone species''?', N'Una especie cuya presencia es determinante para mantener la estructura de un ecosistema.', N'Dificil', 35, 'ACTIVA'),
(3, N'¿Qué es la sucesión ecológica secundaria?', N'El proceso de recuperación natural de un ecosistema tras una perturbación, partiendo de suelo ya formado.', N'Dificil', 35, 'ACTIVA'),
(3, N'¿Qué mide el Índice de Integridad Biótica?', N'La salud de un ecosistema según la composición de sus comunidades biológicas.', N'Dificil', 35, 'ACTIVA'),
(3, N'¿Qué es la conectividad ecológica del paisaje?', N'El grado en que un paisaje facilita el movimiento de especies entre hábitats.', N'Dificil', 35, 'ACTIVA'),
(3, N'¿Qué es el efecto borde en fragmentos de bosque?', N'Los cambios ecológicos que ocurren en los límites de un fragmento de hábitat, distintos al interior.', N'Dificil', 35, 'ACTIVA'),
(3, N'¿Qué organismo internacional evalúa el estado de conservación de las especies mediante la Lista Roja?', N'La Unión Internacional para la Conservación de la Naturaleza (UICN).', N'Dificil', 35, 'ACTIVA'),
(3, N'¿Qué es la silvicultura de restauración?', N'El manejo forestal orientado a recuperar la estructura y función de un bosque nativo.', N'Dificil', 35, 'ACTIVA'),
(3, N'¿Qué es una especie invasora?', N'Una especie introducida fuera de su hábitat natural que causa daño ecológico al ecosistema donde se establece.', N'Dificil', 35, 'ACTIVA'),
(3, N'¿Qué es el servicio ecosistémico de regulación hídrica que brindan los bosques?', N'La capacidad de los bosques de regular el flujo y calidad del agua en una cuenca.', N'Dificil', 35, 'ACTIVA'),
(3, N'¿Qué es la fenología en el estudio de ecosistemas?', N'El estudio de eventos biológicos cíclicos, como floración o migración, y su relación con el clima.', N'Dificil', 35, 'ACTIVA'),
(3, N'¿Qué mide el concepto de biomasa forestal?', N'La cantidad total de materia orgánica viva presente en un bosque.', N'Dificil', 35, 'ACTIVA'),
(3, N'¿Qué es la restauración asistida frente a la restauración pasiva de un ecosistema?', N'La asistida implica intervención humana activa (siembra, control); la pasiva deja que la naturaleza se regenere sola.', N'Dificil', 35, 'ACTIVA'),
(3, N'¿Qué es un punto caliente de biodiversidad (''biodiversity hotspot'')?', N'Una región con alta concentración de especies endémicas y alto riesgo de pérdida de hábitat.', N'Dificil', 35, 'ACTIVA'),
(4, N'¿Comprar solo lo necesario es una forma de consumo responsable?', N'Sí, así es.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Usar bolsas reutilizables ayuda a reducir residuos plásticos?', N'Sí, reduce el uso de bolsas desechables.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Es responsable botar comida en buen estado?', N'No, se debe evitar el desperdicio de alimentos.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Comprar productos con menos empaque plástico es más sostenible?', N'Sí, genera menos residuos.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Reparar un objeto en vez de botarlo es una práctica sostenible?', N'Sí, alarga su vida útil.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Elegir productos duraderos en vez de desechables ayuda al ambiente?', N'Sí, reduce la generación de residuos.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Es sostenible comprar ropa que casi no se va a usar?', N'No, fomenta el consumo innecesario.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Llevar tu propia botella reutilizable reduce el plástico de un solo uso?', N'Sí, correcto.', N'Facil', 10, 'ACTIVA'),
(4, N'¿El consumo responsable busca reducir el impacto ambiental de nuestras compras?', N'Sí, exactamente.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Comprar productos locales suele reducir emisiones de transporte?', N'Sí, al reducir la distancia de traslado.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Es buena práctica leer las etiquetas antes de comprar un producto?', N'Sí, ayuda a elegir opciones más sostenibles.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Qué es el consumo responsable?', N'Adquirir bienes y servicios considerando su impacto social y ambiental.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Qué es la obsolescencia programada?', N'Diseñar productos con una vida útil limitada a propósito para forzar su reemplazo.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Qué es la huella hídrica de un producto?', N'La cantidad total de agua utilizada para producirlo.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Qué es el comercio justo (fair trade)?', N'Un modelo comercial que garantiza condiciones justas para productores, generalmente de países en desarrollo.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Qué significa ''minimalismo'' en el consumo?', N'Un estilo de vida que prioriza tener solo lo esencial, reduciendo el consumo excesivo.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Qué es el ''fast fashion'' o moda rápida?', N'Un modelo de producción textil de bajo costo y rápida rotación, con alto impacto ambiental.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Qué es una etiqueta ecológica o sello verde?', N'Una certificación que indica que un producto cumple ciertos criterios ambientales.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Qué beneficio ambiental tiene comprar productos a granel?', N'Reduce el uso de empaques individuales.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Qué es el consumo colaborativo?', N'Compartir, intercambiar o alquilar bienes en vez de comprarlos individualmente.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Qué es la huella de carbono de un producto?', N'La cantidad de gases de efecto invernadero emitidos durante su ciclo de vida.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Qué es el ''greenwashing''?', N'Cuando una empresa exagera o falsea su compromiso ambiental para parecer más sostenible.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Qué ventaja tiene alargar la vida útil de un aparato electrónico?', N'Reduce la generación de residuos electrónicos y el consumo de recursos.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Qué es el consumo consciente?', N'Tomar decisiones de compra reflexionando sobre su impacto ambiental y social.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Qué es una economía de suscripción aplicada al consumo responsable?', N'Un modelo donde se paga por el uso de un producto o servicio en vez de poseerlo.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Qué es el análisis de ciclo de vida (ACV) de un producto?', N'Una metodología que evalúa el impacto ambiental de un producto desde su extracción hasta su disposición final.', N'Dificil', 35, 'ACTIVA'),
(4, N'¿Qué es la ''huella ecológica'' de una persona o país?', N'La superficie de tierra y agua necesaria para producir lo que consume y absorber sus residuos.', N'Dificil', 35, 'ACTIVA'),
(4, N'¿Qué es el desacoplamiento (decoupling) entre crecimiento económico e impacto ambiental?', N'Lograr crecer económicamente sin aumentar proporcionalmente el uso de recursos naturales.', N'Dificil', 35, 'ACTIVA'),
(4, N'¿Qué es la responsabilidad social corporativa aplicada al consumo?', N'El compromiso de las empresas de operar de forma ética y sostenible más allá de lo exigido por ley.', N'Dificil', 35, 'ACTIVA'),
(4, N'¿Qué es el ''consumo aspiracional'' y su relación con la insostenibilidad?', N'Comprar bienes para proyectar estatus social, generando consumo excesivo innecesario.', N'Dificil', 35, 'ACTIVA'),
(4, N'¿Qué es la trazabilidad de un producto?', N'La capacidad de rastrear su origen y proceso de producción a lo largo de toda la cadena de suministro.', N'Dificil', 35, 'ACTIVA'),
(4, N'¿Qué es la economía del bienestar frente al PIB como medida de progreso?', N'Un enfoque que mide el progreso considerando bienestar y sostenibilidad, no solo crecimiento económico.', N'Dificil', 35, 'ACTIVA'),
(4, N'¿Qué es el ''efecto rebote'' en el consumo sostenible?', N'Cuando el ahorro generado por ser más eficiente termina usándose para consumir más.', N'Dificil', 35, 'ACTIVA'),
(4, N'¿Qué es una certificación B Corp?', N'Una certificación que reconoce a empresas con altos estándares sociales y ambientales.', N'Dificil', 35, 'ACTIVA'),
(4, N'¿Qué es la obsolescencia percibida?', N'Cuando un producto se descarta por moda o percepción, aunque siga siendo funcional.', N'Dificil', 35, 'ACTIVA'),
(5, N'¿Apagar las luces al salir de una habitación ahorra energía?', N'Sí, correcto.', N'Facil', 10, 'ACTIVA'),
(5, N'¿Los focos LED consumen menos energía que los focos incandescentes?', N'Sí, son mucho más eficientes.', N'Facil', 10, 'ACTIVA'),
(5, N'¿Desconectar aparatos que no se usan ahorra electricidad?', N'Sí, evita el consumo en modo espera.', N'Facil', 10, 'ACTIVA'),
(5, N'¿Usar luz natural en el día ayuda a ahorrar energía?', N'Sí, reduce el uso de luz artificial.', N'Facil', 10, 'ACTIVA'),
(5, N'¿Es más eficiente lavar ropa con agua fría que con agua caliente?', N'Sí, consume menos energía.', N'Facil', 10, 'ACTIVA'),
(5, N'¿La energía solar es una fuente de energía renovable?', N'Sí, proviene del sol.', N'Facil', 10, 'ACTIVA'),
(5, N'¿El viento se puede usar para generar electricidad?', N'Sí, mediante turbinas eólicas.', N'Facil', 10, 'ACTIVA'),
(5, N'¿Mantener el refrigerador muy lleno de hielo acumulado gasta más energía?', N'Sí, reduce su eficiencia.', N'Facil', 10, 'ACTIVA'),
(5, N'¿Usar electrodomésticos eficientes ayuda a reducir la factura de luz?', N'Sí, consumen menos energía.', N'Facil', 10, 'ACTIVA'),
(5, N'¿El carbón es una fuente de energía renovable?', N'No, es un combustible fósil no renovable.', N'Facil', 10, 'ACTIVA'),
(5, N'¿Ventilar la casa naturalmente puede reducir el uso de aire acondicionado?', N'Sí, ayuda a reducirlo.', N'Facil', 10, 'ACTIVA'),
(5, N'¿Qué es la eficiencia energética?', N'Usar menos energía para obtener el mismo resultado o servicio.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Qué es una energía renovable?', N'Una fuente de energía que se regenera naturalmente, como el sol o el viento.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Qué es el etiquetado energético de electrodomésticos?', N'Una clasificación que indica el nivel de eficiencia energética de un producto.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Qué es la energía geotérmica?', N'La energía obtenida del calor interno de la Tierra.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Qué es una red eléctrica inteligente (smart grid)?', N'Una red que optimiza la distribución de electricidad usando tecnología digital.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Qué es el consumo ''fantasma'' o ''vampiro'' de energía?', N'La electricidad consumida por aparatos en modo espera o apagados pero conectados.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Qué es la cogeneración energética?', N'La producción simultánea de electricidad y calor útil a partir de una misma fuente de energía.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Qué ventaja energética tiene el aislamiento térmico en una vivienda?', N'Reduce la necesidad de calefacción o refrigeración.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Qué es un panel fotovoltaico?', N'Un dispositivo que convierte la luz solar directamente en electricidad.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Qué es la matriz energética de un país?', N'El conjunto de fuentes de energía que utiliza para satisfacer su demanda.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Qué es la eficiencia energética en la industria?', N'La optimización del uso de energía en procesos productivos para reducir costos y emisiones.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Qué diferencia hay entre energía primaria y energía final?', N'La primaria es la extraída de la naturaleza; la final es la que llega lista para consumir tras transformarse.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Qué es un certificado de eficiencia energética de una vivienda?', N'Un documento que califica el consumo energético estimado de un inmueble.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Qué mide el coeficiente de rendimiento (COP) en sistemas de climatización?', N'La relación entre la energía útil producida y la energía eléctrica consumida.', N'Dificil', 35, 'ACTIVA'),
(5, N'¿Qué es la curva de demanda energética y su relación con la eficiencia?', N'La variación del consumo eléctrico a lo largo del día, clave para optimizar la generación.', N'Dificil', 35, 'ACTIVA'),
(5, N'¿Qué es el almacenamiento energético mediante baterías a gran escala?', N'Sistemas que guardan energía eléctrica para su uso posterior, útiles para equilibrar la red.', N'Dificil', 35, 'ACTIVA'),
(5, N'¿Qué es la ''paridad de red'' (grid parity) en energías renovables?', N'El punto en que el costo de generar energía renovable iguala o es menor al de fuentes convencionales.', N'Dificil', 35, 'ACTIVA'),
(5, N'¿Qué es la gestión de la demanda energética (demand response)?', N'Estrategias para ajustar el consumo eléctrico según la disponibilidad de energía en la red.', N'Dificil', 35, 'ACTIVA'),
(5, N'¿Qué es la eficiencia exergética de un sistema energético?', N'Una medida que evalúa la calidad de la energía utilizable, no solo su cantidad.', N'Dificil', 35, 'ACTIVA'),
(5, N'¿Qué es un sistema de cogeneración de ciclo combinado?', N'Un sistema que aprovecha el calor residual de generación eléctrica para producir energía adicional.', N'Dificil', 35, 'ACTIVA'),
(5, N'¿Qué es la intermitencia como desafío de las energías renovables?', N'La variabilidad en la generación de energía solar o eólica según condiciones climáticas.', N'Dificil', 35, 'ACTIVA'),
(5, N'¿Qué es el factor de capacidad de una planta de energía?', N'La relación entre la energía realmente producida y la que produciría a máxima capacidad constante.', N'Dificil', 35, 'ACTIVA'),
(5, N'¿Qué es la electrificación de la demanda como estrategia de descarbonización?', N'Sustituir el uso de combustibles fósiles por electricidad en procesos como transporte y calefacción.', N'Dificil', 35, 'ACTIVA'),
(6, N'¿Comprar frutas y verduras de temporada es más sostenible?', N'Sí, generalmente requieren menos recursos para producirse.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Desperdiciar comida tiene un impacto ambiental negativo?', N'Sí, desperdicia recursos usados en producirla.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Comer productos locales reduce las emisiones por transporte?', N'Sí, al recorrer menos distancia.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Guardar bien los alimentos ayuda a que duren más y se desperdicien menos?', N'Sí, correcto.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Es sostenible cocinar solo la cantidad de comida que se va a consumir?', N'Sí, evita el desperdicio.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Consumir menos carne puede reducir la huella ambiental de la dieta?', N'Sí, la ganadería tiene un alto impacto ambiental.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Tener una huerta en casa es una práctica de alimentación sostenible?', N'Sí, reduce el transporte y los empaques.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Aprovechar las sobras de comida es una buena práctica sostenible?', N'Sí, evita el desperdicio de alimentos.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Los alimentos ultraprocesados suelen generar más residuos de empaque?', N'Sí, generalmente vienen con más empaques.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Comprar solo lo necesario en el supermercado ayuda a evitar el desperdicio?', N'Sí, correcto.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Qué es la alimentación sostenible?', N'Una forma de alimentarse que minimiza el impacto ambiental y social de la producción de alimentos.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Qué es la huella de carbono de los alimentos?', N'La cantidad de gases de efecto invernadero emitidos en su producción y transporte.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Qué es el desperdicio alimentario?', N'La pérdida de alimentos aptos para el consumo en cualquier etapa de la cadena alimentaria.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Qué ventaja ambiental tiene una dieta con más vegetales y menos carne?', N'Generalmente reduce el uso de agua, tierra y las emisiones asociadas.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Qué es la agricultura orgánica?', N'Un sistema de producción que evita agroquímicos sintéticos y prioriza prácticas ecológicas.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Qué es el ''kilómetro cero'' en alimentación?', N'Consumir alimentos producidos cerca del lugar de consumo.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Qué es la soberanía alimentaria?', N'El derecho de los pueblos a decidir sus propios sistemas alimentarios y agrícolas.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Qué impacto tiene la ganadería intensiva sobre la deforestación?', N'Es una de las principales causas de deforestación para ampliar pastizales.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Qué es la agroecología?', N'Un enfoque agrícola que integra principios ecológicos en la producción de alimentos.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Qué es el etiquetado de origen de los alimentos?', N'Información que indica el lugar de procedencia de un producto alimenticio.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Qué es la pesca sostenible?', N'Prácticas pesqueras que no comprometen la capacidad de reproducción de las especies marinas.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Qué es la dieta de ''proximidad y temporada''?', N'Consumir alimentos locales y propios de la época del año, reduciendo impacto ambiental.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Qué es la huella hídrica de la carne de res comparada con legumbres?', N'Es considerablemente mayor, ya que requiere mucha más agua por kilo producido.', N'Dificil', 35, 'ACTIVA'),
(6, N'¿Qué es la seguridad alimentaria según la FAO?', N'El acceso físico y económico de todas las personas a alimentos suficientes, seguros y nutritivos.', N'Dificil', 35, 'ACTIVA'),
(6, N'¿Qué es la agricultura regenerativa?', N'Un enfoque agrícola centrado en restaurar la salud del suelo y los ecosistemas.', N'Dificil', 35, 'ACTIVA'),
(6, N'¿Qué porcentaje aproximado de los alimentos producidos en el mundo se pierde o desperdicia?', N'Alrededor de un tercio de la producción mundial.', N'Dificil', 35, 'ACTIVA'),
(6, N'¿Qué es el índice de conversión alimenticia en ganadería?', N'La cantidad de alimento necesaria para producir una unidad de proteína animal.', N'Dificil', 35, 'ACTIVA'),
(6, N'¿Qué es la trazabilidad alimentaria?', N'La capacidad de rastrear un alimento a lo largo de toda su cadena de producción y distribución.', N'Dificil', 35, 'ACTIVA'),
(6, N'¿Qué es la biofortificación de cultivos?', N'Mejorar el valor nutricional de un cultivo mediante mejoramiento genético o agronómico.', N'Dificil', 35, 'ACTIVA'),
(6, N'¿Qué es la economía circular aplicada a los residuos alimentarios?', N'Reutilizar los desechos de alimentos como compost, biogás o alimento animal.', N'Dificil', 35, 'ACTIVA'),
(6, N'¿Qué es el concepto de ''planetary health diet''?', N'Una dieta diseñada para ser saludable para las personas y sostenible para el planeta.', N'Dificil', 35, 'ACTIVA'),
(6, N'¿Qué es la monocultura y su riesgo ambiental?', N'El cultivo de una sola especie en grandes extensiones, que reduce biodiversidad y agota el suelo.', N'Dificil', 35, 'ACTIVA'),
(7, N'¿Reparar un electrodoméstico en vez de botarlo ayuda al ambiente?', N'Sí, alarga su vida útil y evita generar más residuos.', N'Facil', 10, 'ACTIVA'),
(7, N'¿Reutilizar un frasco de vidrio como recipiente es una buena práctica?', N'Sí, le da una segunda vida útil.', N'Facil', 10, 'ACTIVA'),
(7, N'¿Donar ropa que ya no usas es mejor que botarla?', N'Sí, permite que otra persona la reutilice.', N'Facil', 10, 'ACTIVA'),
(7, N'¿Comprar de segunda mano es una práctica de economía circular?', N'Sí, alarga la vida útil de los productos.', N'Facil', 10, 'ACTIVA'),
(7, N'¿Intercambiar objetos que ya no usas con otras personas es sostenible?', N'Sí, evita que se conviertan en residuos.', N'Facil', 10, 'ACTIVA'),
(7, N'¿Prestar herramientas en vez de comprarlas nuevas cada vez ahorra recursos?', N'Sí, correcto.', N'Facil', 10, 'ACTIVA'),
(7, N'¿Es sostenible arreglar la suela de un zapato en vez de comprar uno nuevo?', N'Sí, alarga su vida útil.', N'Facil', 10, 'ACTIVA'),
(7, N'¿Reutilizar cajas de cartón para mudanzas es una práctica sostenible?', N'Sí, evita comprar cajas nuevas.', N'Facil', 10, 'ACTIVA'),
(7, N'¿La economía circular busca reducir la generación de residuos?', N'Sí, ese es uno de sus objetivos principales.', N'Facil', 10, 'ACTIVA'),
(7, N'¿Es más sostenible comprar cosas para usarlas una sola vez?', N'No, se prefiere lo reutilizable y duradero.', N'Facil', 10, 'ACTIVA'),
(7, N'¿Qué es la economía circular?', N'Un modelo económico que busca mantener los productos y materiales en uso el mayor tiempo posible.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Qué es el diseño para la reparabilidad de un producto?', N'Diseñar productos que puedan repararse fácilmente en lugar de desecharse.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Qué es un ''café reparador'' o ''repair café''?', N'Un espacio comunitario donde se reparan objetos de forma gratuita o colaborativa.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Qué es la reutilización en el contexto de la economía circular?', N'Usar un producto o material nuevamente para el mismo fin o uno distinto sin transformarlo.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Qué diferencia hay entre economía lineal y economía circular?', N'La lineal sigue el modelo ''producir, usar y desechar''; la circular busca reintegrar los materiales al ciclo productivo.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Qué es el ''derecho a reparación'' (right to repair)?', N'Un movimiento que exige que los productos puedan repararse en vez de forzar su reemplazo.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Qué es el arrendamiento de productos (leasing) en economía circular?', N'Pagar por el uso de un producto en vez de ser su dueño, incentivando su mantenimiento y reciclaje.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Qué es la simbiosis industrial?', N'Cuando los residuos de una industria se convierten en materia prima de otra.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Qué es el ecodiseño?', N'Diseñar productos considerando su impacto ambiental durante todo su ciclo de vida.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Qué es la remanufactura?', N'El proceso de restaurar productos usados a una condición similar a la original.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Qué beneficio económico ofrece la economía circular a las empresas?', N'Reduce costos de materia prima al reutilizar y reciclar recursos.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Qué es un mercado de segunda mano o de trueque?', N'Un espacio para intercambiar o vender productos usados, alargando su vida útil.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Qué son los ''ciclos biológicos y técnicos'' en el modelo de economía circular?', N'Los biológicos reintegran materiales orgánicos a la naturaleza; los técnicos mantienen materiales no biológicos en circulación mediante reuso y reciclaje.', N'Dificil', 35, 'ACTIVA'),
(7, N'¿Qué es la ''cuna a cuna'' (cradle to cradle) como filosofía de diseño?', N'Un enfoque de diseño donde los materiales de un producto pueden reincorporarse indefinidamente a nuevos ciclos productivos.', N'Dificil', 35, 'ACTIVA'),
(7, N'¿Qué es la desmaterialización de la economía?', N'Reducir la cantidad de materiales necesarios para generar valor económico.', N'Dificil', 35, 'ACTIVA'),
(7, N'¿Qué es un modelo de negocio ''producto como servicio'' (PaaS)?', N'Un modelo donde el cliente paga por el uso o resultado de un producto, no por su propiedad.', N'Dificil', 35, 'ACTIVA'),
(7, N'¿Qué es la obsolescencia funcional frente a la obsolescencia técnica?', N'La funcional ocurre cuando un producto deja de satisfacer necesidades aunque funcione; la técnica ocurre cuando deja de operar correctamente.', N'Dificil', 35, 'ACTIVA'),
(7, N'¿Qué es la huella material de una economía?', N'La cantidad total de materias primas extraídas para satisfacer el consumo de una economía.', N'Dificil', 35, 'ACTIVA'),
(7, N'¿Qué es la ''brecha de circularidad'' global?', N'El porcentaje de materiales que aún no se reintroducen en la economía tras su primer uso.', N'Dificil', 35, 'ACTIVA'),
(7, N'¿Qué es la logística inversa en economía circular?', N'El proceso de recuperar productos o materiales usados desde el consumidor hacia el productor.', N'Dificil', 35, 'ACTIVA'),
(7, N'¿Qué es un ''pasaporte de producto digital''?', N'Un registro digital con información sobre los materiales y ciclo de vida de un producto para facilitar su reciclaje o reparación.', N'Dificil', 35, 'ACTIVA'),
(7, N'¿Qué es el desacoplamiento de recursos en economía circular?', N'Separar el crecimiento económico del incremento en el uso de recursos naturales.', N'Dificil', 35, 'ACTIVA'),
(2, N'¿Qué medio de transporte genera menos emisiones: la caminata o el auto particular?', N'La caminata.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Qué medio de transporte genera menos emisiones: la bicicleta o la motocicleta?', N'La bicicleta.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Qué medio de transporte genera menos emisiones: el bus urbano o el auto particular con un solo ocupante?', N'El bus urbano.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Qué medio de transporte genera menos emisiones: el tren eléctrico o el avión?', N'El tren eléctrico.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Qué medio de transporte genera menos emisiones: el metro o el auto particular?', N'El metro.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Qué medio de transporte genera menos emisiones: el scooter eléctrico o el auto a gasolina?', N'El scooter eléctrico.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Qué medio de transporte genera menos emisiones: el auto eléctrico o el auto a diésel?', N'El auto eléctrico.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Qué medio de transporte genera menos emisiones: compartir el auto (carpool) o viajar cada uno en su propio auto?', N'Compartir el auto (carpool).', N'Facil', 10, 'ACTIVA'),
(2, N'¿Qué medio de transporte genera menos emisiones: el tranvía o el auto particular?', N'El tranvía.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Qué medio de transporte genera menos emisiones: caminar al trabajo o manejar al trabajo?', N'Caminar al trabajo.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Qué medio de transporte genera menos emisiones: la bicicleta eléctrica o el auto particular?', N'La bicicleta eléctrica.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Qué medio de transporte genera menos emisiones: el bus eléctrico o el bus a diésel?', N'El bus eléctrico.', N'Facil', 10, 'ACTIVA'),
(2, N'¿Qué se recomienda hacer antes de comprar un auto nuevo, pensando en sostenibilidad?', N'Evaluar si realmente se necesita o si alternativas como el transporte público bastan.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Usar bicicleta para trayectos cortos en la ciudad reduce la contaminación?', N'Sí, reduce las emisiones locales.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿El transporte escolar compartido reduce la cantidad de autos frente a los colegios?', N'Sí, reduce el número de vehículos circulando.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Planificar bien las rutas de reparto reduce el consumo de combustible?', N'Sí, optimiza los trayectos y reduce emisiones.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Inflar correctamente las llantas de la bicicleta mejora su eficiencia?', N'Sí, reduce el esfuerzo y desgaste.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Es sostenible dejar el auto encendido innecesariamente mientras se espera?', N'No, desperdicia combustible y genera emisiones.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Los estacionamientos para bicicletas fomentan su uso en la ciudad?', N'Sí, facilitan que más personas elijan la bicicleta.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Combinar bicicleta y transporte público es una estrategia de movilidad sostenible?', N'Sí, es una buena combinación intermodal.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Reducir los viajes innecesarios en auto ayuda a bajar las emisiones?', N'Sí, correcto.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Usar aplicaciones para compartir viajes (carpooling) ayuda al ambiente?', N'Sí, reduce la cantidad de vehículos circulando.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Las zonas peatonales en el centro de las ciudades reducen la contaminación local?', N'Sí, al limitar la circulación de vehículos motorizados.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Es recomendable mantener el motor del auto en buen estado para reducir emisiones?', N'Sí, un motor bien mantenido contamina menos.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Cambiar viajes cortos en auto por caminata mejora la calidad del aire local?', N'Sí, reduce emisiones en distancias cortas.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿El uso de bicicletas públicas compartidas ayuda a descongestionar las ciudades?', N'Sí, ofrece una alternativa sin emisiones.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Acelerar y frenar bruscamente aumenta el consumo de combustible?', N'Sí, un manejo suave ahorra combustible.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿La expansión de ciclovías fomenta la movilidad sostenible?', N'Sí, incentiva el uso seguro de la bicicleta.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Los semáforos inteligentes pueden reducir la congestión y las emisiones?', N'Sí, optimizan el flujo vehicular.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Viajar en avión suele tener una huella de carbono mayor que viajar en tren para la misma distancia?', N'Sí, generalmente el avión emite más por pasajero.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿El mantenimiento regular de un vehículo eléctrico reduce su vida útil de la batería si se descuida?', N'Sí, un mal mantenimiento puede acortar la vida de la batería.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Fomentar el uso de bicicletas en empresas mediante incentivos ayuda a la movilidad sostenible?', N'Sí, motiva a más empleados a dejar el auto.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Un urbanismo compacto reduce la necesidad de largos desplazamientos motorizados?', N'Sí, acerca los servicios a la población.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Cuál es una función importante de las abejas en el ecosistema?', N'Ayudan a polinizar flores y cultivos.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Cuál es una función importante de las lombrices de tierra en el ecosistema?', N'Ayudan a airear y enriquecer el suelo.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Cuál es una función importante de los murciélagos en el ecosistema?', N'Ayudan a polinizar plantas y controlar insectos.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Cuál es una función importante de los manglares en el ecosistema?', N'Ayudan a proteger la costa y ser vivero de especies marinas.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Cuál es una función importante de los buitres en el ecosistema?', N'Ayudan a limpiar el ecosistema al alimentarse de carroña.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Cuál es una función importante de las abejas nativas sin aguijón en el ecosistema?', N'Ayudan a polinizar plantas silvestres.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Cuál es una función importante de los corales en el ecosistema?', N'Ayudan a formar arrecifes que albergan gran biodiversidad marina.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Cuál es una función importante de las mariposas en el ecosistema?', N'Ayudan a actuar como polinizadoras y bioindicadoras.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Cuál es una función importante de los hongos micorrízicos en el ecosistema?', N'Ayudan a ayudar a las raíces de las plantas a absorber nutrientes.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Cuál es una función importante de los humedales en el ecosistema?', N'Ayudan a filtrar el agua y regular inundaciones.', N'Facil', 10, 'ACTIVA'),
(3, N'¿Sembrar árboles en las orillas de los ríos ayuda a proteger el agua?', N'Sí, evita la erosión y filtra contaminantes.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿La pérdida de bosques afecta a las especies que dependen de ellos?', N'Sí, muchas especies pierden su hábitat.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Cuidar los parques y áreas verdes urbanas ayuda a la biodiversidad local?', N'Sí, brindan refugio a diversas especies.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Los incendios forestales provocados por el ser humano dañan la biodiversidad?', N'Sí, destruyen hábitats y especies.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Es importante no extraer plantas o animales silvestres de su hábitat natural?', N'Sí, para no alterar el equilibrio del ecosistema.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Los jardines con plantas nativas ayudan a atraer polinizadores locales?', N'Sí, favorecen a insectos y aves nativas.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿La conservación de semillas nativas ayuda a la reforestación futura?', N'Sí, permite sembrar especies adaptadas a la zona.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿El monocultivo forestal tiene la misma biodiversidad que un bosque nativo?', N'No, suele tener mucha menos biodiversidad.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Participar en jornadas de reforestación comunitaria ayuda al ambiente?', N'Sí, contribuye a recuperar zonas degradadas.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Es recomendable regar los árboles recién plantados en su primera etapa?', N'Sí, necesitan agua para establecerse bien.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿La deforestación puede aumentar el riesgo de deslizamientos de tierra?', N'Sí, al perderse las raíces que sostienen el suelo.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Los ríos limpios favorecen la biodiversidad acuática?', N'Sí, permiten que más especies sobrevivan.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Es beneficioso dejar zonas de vegetación natural entre cultivos agrícolas?', N'Sí, sirven de refugio para la fauna silvestre.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿La reforestación ayuda a mitigar el cambio climático?', N'Sí, los árboles capturan dióxido de carbono.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Cuidar los ecosistemas marinos ayuda a mantener la pesca a largo plazo?', N'Sí, mantiene las poblaciones de peces saludables.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Reducir el uso de pesticidas ayuda a proteger a los polinizadores?', N'Sí, muchos pesticidas dañan a las abejas y otros insectos.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Un bosque bien conservado ayuda a regular las lluvias de una región?', N'Sí, influye en el ciclo hídrico local.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Es importante respetar las vedas de pesca y caza para proteger especies?', N'Sí, permiten que las poblaciones se recuperen.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿La educación ambiental ayuda a proteger la biodiversidad a largo plazo?', N'Sí, fomenta conductas de cuidado y conservación.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Los pastizales naturales también son ecosistemas importantes para la biodiversidad?', N'Sí, albergan muchas especies propias de ese ecosistema.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Qué opción es más sostenible: una botella reutilizable o botellas plásticas desechables?', N'Una botella reutilizable.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Qué opción es más sostenible: una bolsa de tela o bolsas plásticas de un solo uso?', N'Una bolsa de tela.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Qué opción es más sostenible: comprar a granel o comprar todo empacado individualmente?', N'Comprar a granel.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Qué opción es más sostenible: reparar un electrodoméstico o comprar uno nuevo innecesariamente?', N'Reparar un electrodoméstico.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Qué opción es más sostenible: comprar ropa usada o comprar siempre ropa nueva de moda rápida?', N'Comprar ropa usada.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Qué opción es más sostenible: usar pilas recargables o usar pilas desechables constantemente?', N'Usar pilas recargables.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Qué opción es más sostenible: llevar tu propio termo o comprar café en vaso desechable cada día?', N'Llevar tu propio termo.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Qué opción es más sostenible: comprar productos duraderos o comprar productos de baja calidad y desecharlos rápido?', N'Comprar productos duraderos.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Qué opción es más sostenible: alquilar herramientas ocasionales o comprar herramientas que se usarán una sola vez?', N'Alquilar herramientas ocasionales.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Qué opción es más sostenible: elegir productos con empaque reciclable o elegir productos con empaque no reciclable?', N'Elegir productos con empaque reciclable.', N'Facil', 10, 'ACTIVA'),
(4, N'¿Planificar las compras semanales ayuda a evitar el desperdicio de alimentos y dinero?', N'Sí, ayuda a comprar solo lo necesario.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Investigar sobre una marca antes de comprar ayuda a un consumo más responsable?', N'Sí, permite conocer sus prácticas ambientales y sociales.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Comprar productos de temporada suele ser más sostenible?', N'Sí, requieren menos recursos artificiales para producirse.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Es recomendable revisar la fecha de vencimiento para evitar comprar de más?', N'Sí, ayuda a reducir el desperdicio.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Reutilizar envases de vidrio para guardar alimentos es una buena práctica?', N'Sí, evita comprar recipientes nuevos.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Elegir productos concentrados (como detergentes) reduce el uso de plástico y transporte?', N'Sí, requieren menos empaque y espacio.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Vender o donar aparatos electrónicos que ya no usas es mejor que dejarlos guardados sin uso?', N'Sí, les da una segunda vida útil.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Es sostenible seguir cada tendencia de consumo que aparece en redes sociales?', N'No, fomenta el consumo innecesario.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Comparar la durabilidad de los productos antes de comprar ayuda a consumir mejor?', N'Sí, evita compras que se desechan rápido.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Cocinar en casa suele generar menos residuos de empaque que pedir comida a domicilio?', N'Sí, generalmente genera menos envases desechables.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Es responsable comprar productos solo por su empaque atractivo sin necesitarlos?', N'No, se debe priorizar la necesidad real.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Aprovechar cupones y ofertas para artículos innecesarios sigue siendo consumo responsable?', N'No, si genera una compra que no se necesita.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Qué opción ahorra más energía: un foco LED o un foco incandescente?', N'Un foco LED.', N'Facil', 10, 'ACTIVA'),
(5, N'¿Qué opción ahorra más energía: un cargador desconectado cuando no se usa o un cargador siempre conectado?', N'Un cargador desconectado cuando no se usa.', N'Facil', 10, 'ACTIVA'),
(5, N'¿Qué opción ahorra más energía: lavar ropa en agua fría o lavar ropa en agua caliente?', N'Lavar ropa en agua fría.', N'Facil', 10, 'ACTIVA'),
(5, N'¿Qué opción ahorra más energía: secar la ropa al sol o usar siempre la secadora eléctrica?', N'Secar la ropa al sol.', N'Facil', 10, 'ACTIVA'),
(5, N'¿Qué opción ahorra más energía: usar el aire acondicionado a una temperatura moderada o usarlo a la temperatura más baja posible?', N'Usar el aire acondicionado a una temperatura moderada.', N'Facil', 10, 'ACTIVA'),
(5, N'¿Qué opción ahorra más energía: un refrigerador con etiquetado A o un refrigerador con etiquetado bajo en eficiencia?', N'Un refrigerador con etiquetado A.', N'Facil', 10, 'ACTIVA'),
(5, N'¿Qué opción ahorra más energía: aprovechar la luz natural o mantener las luces encendidas todo el día?', N'Aprovechar la luz natural.', N'Facil', 10, 'ACTIVA'),
(5, N'¿Qué opción ahorra más energía: apagar el computador al no usarlo o dejarlo encendido toda la noche?', N'Apagar el computador al no usarlo.', N'Facil', 10, 'ACTIVA'),
(5, N'¿Qué opción ahorra más energía: usar paneles solares o depender solo de electricidad de origen fósil?', N'Usar paneles solares.', N'Facil', 10, 'ACTIVA'),
(5, N'¿Qué opción ahorra más energía: aislar bien una casa térmicamente o no aislar la vivienda del frío o el calor?', N'Aislar bien una casa térmicamente.', N'Facil', 10, 'ACTIVA'),
(5, N'¿Usar temporizadores para el riego o la iluminación exterior ayuda a ahorrar energía?', N'Sí, evita el uso innecesario.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Es más eficiente cocinar tapando las ollas?', N'Sí, se cocina más rápido y se ahorra energía.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Descongelar alimentos antes de cocinarlos ahorra energía respecto a cocinarlos congelados?', N'Sí, reduce el tiempo de cocción.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Pintar techos de colores claros ayuda a reducir el uso de aire acondicionado?', N'Sí, refleja más luz solar y reduce el calor interior.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Usar bombillas de bajo consumo en toda la casa reduce la factura eléctrica?', N'Sí, consumen menos energía.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Es recomendable revisar fugas de aire en puertas y ventanas para ahorrar energía?', N'Sí, evita pérdidas de calor o frío.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Usar el lavavajillas o la lavadora a carga completa ahorra energía y agua?', N'Sí, se aprovecha mejor cada ciclo.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Instalar sensores de movimiento para las luces ayuda a ahorrar energía en espacios comunes?', N'Sí, evita que las luces queden encendidas sin necesidad.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Mantener limpios los paneles solares mejora su eficiencia?', N'Sí, la suciedad reduce su capacidad de generar energía.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Usar electrodomésticos en horarios de menor demanda energética puede ser más eficiente para la red?', N'Sí, ayuda a equilibrar la demanda eléctrica.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Es una buena práctica revisar periódicamente el estado de las instalaciones eléctricas del hogar?', N'Sí, previene fugas y consumo innecesario.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Cerrar bien puertas y ventanas cuando el aire acondicionado está encendido mejora su eficiencia?', N'Sí, evita fugas de aire frío.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Un termostato programable ayuda a optimizar el uso de calefacción o aire acondicionado?', N'Sí, ajusta la temperatura automáticamente según horarios.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿El uso de energía solar térmica para calentar agua reduce el consumo eléctrico?', N'Sí, aprovecha el calor del sol en vez de electricidad.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Es eficiente dejar el horno abierto después de cocinar para calentar la cocina?', N'No es una práctica recomendada ni la más eficiente ni segura.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Qué opción tiene menor impacto ambiental: las legumbres o la carne de res?', N'Las legumbres.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Qué opción tiene menor impacto ambiental: los vegetales de temporada o los vegetales importados fuera de temporada?', N'Los vegetales de temporada.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Qué opción tiene menor impacto ambiental: comprar en el mercado local o comprar en cadenas con productos importados?', N'Comprar en el mercado local.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Qué opción tiene menor impacto ambiental: cocinar en casa o consumir comida ultraprocesada a diario?', N'Cocinar en casa.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Qué opción tiene menor impacto ambiental: compostar los residuos orgánicos o botar los residuos orgánicos a la basura común?', N'Compostar los residuos orgánicos.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Qué opción tiene menor impacto ambiental: consumir pescado de fuentes sostenibles o consumir especies en riesgo de sobreexplotación?', N'Consumir pescado de fuentes sostenibles.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Qué opción tiene menor impacto ambiental: aprovechar las sobras de comida o botar las sobras sistemáticamente?', N'Aprovechar las sobras de comida.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Qué opción tiene menor impacto ambiental: cultivar hierbas en casa o comprarlas siempre empacadas en plástico?', N'Cultivar hierbas en casa.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Planificar el menú semanal ayuda a reducir el desperdicio de alimentos?', N'Sí, permite comprar solo lo necesario.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Congelar alimentos antes de que se dañen ayuda a evitar su desperdicio?', N'Sí, alarga su vida útil.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Es sostenible servir porciones más grandes de las que se van a comer?', N'No, aumenta el riesgo de desperdicio.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Comprar productos con certificación de comercio justo apoya prácticas más sostenibles?', N'Sí, favorece condiciones justas para los productores.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Consumir huevos y lácteos de producción local suele reducir la huella de transporte?', N'Sí, al reducir la distancia de traslado.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿El consumo excesivo de alimentos procesados genera más residuos de empaque?', N'Sí, suelen venir con más envoltorios individuales.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Aprovechar cáscaras y tallos de vegetales en caldos reduce el desperdicio?', N'Sí, es una forma de aprovechar mejor los alimentos.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Elegir pescado con tallas mínimas permitidas ayuda a la sostenibilidad pesquera?', N'Sí, permite que los peces se reproduzcan antes de ser capturados.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Es recomendable revisar el refrigerador antes de ir de compras?', N'Sí, evita comprar alimentos duplicados que se puedan desperdiciar.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Compostar en casa reduce la cantidad de basura orgánica enviada a rellenos sanitarios?', N'Sí, y además genera abono natural.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Elegir envases retornables para productos lácteos es una práctica sostenible?', N'Sí, reduce la generación de residuos de envase.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿El consumo responsable de carne incluye reducir las porciones y frecuencia?', N'Sí, ayuda a disminuir el impacto ambiental de la dieta.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Qué práctica es más sostenible: reparar un celular con la pantalla rota o comprar uno nuevo teniendo uno reparable?', N'Reparar un celular con la pantalla rota.', N'Facil', 10, 'ACTIVA'),
(7, N'¿Qué práctica es más sostenible: comprar muebles de segunda mano o comprar siempre muebles nuevos?', N'Comprar muebles de segunda mano.', N'Facil', 10, 'ACTIVA'),
(7, N'¿Qué práctica es más sostenible: llevar los zapatos al zapatero o botarlos ante el primer desgaste?', N'Llevar los zapatos al zapatero.', N'Facil', 10, 'ACTIVA'),
(7, N'¿Qué práctica es más sostenible: reutilizar frascos como organizadores o botar los frascos de vidrio?', N'Reutilizar frascos como organizadores.', N'Facil', 10, 'ACTIVA'),
(7, N'¿Qué práctica es más sostenible: alquilar un traje para una ocasión especial o comprar uno que se usará una sola vez?', N'Alquilar un traje para una ocasión especial.', N'Facil', 10, 'ACTIVA'),
(7, N'¿Qué práctica es más sostenible: vender ropa que ya no usas o dejarla acumulada sin uso indefinidamente?', N'Vender ropa que ya no usas.', N'Facil', 10, 'ACTIVA'),
(7, N'¿Qué práctica es más sostenible: reparar una bicicleta o comprar una nueva por un desperfecto menor?', N'Reparar una bicicleta.', N'Facil', 10, 'ACTIVA'),
(7, N'¿Qué práctica es más sostenible: participar en un banco de intercambio de objetos o comprar siempre todo nuevo?', N'Participar en un banco de intercambio de objetos.', N'Facil', 10, 'ACTIVA'),
(7, N'¿Los talleres de reparación comunitarios fomentan la economía circular?', N'Sí, alargan la vida útil de los objetos.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Comprar productos que se puedan desarmar y reparar fácilmente favorece la economía circular?', N'Sí, facilita su mantenimiento y reciclaje.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Es más sostenible comprar un producto con garantía extendida y soporte de repuestos?', N'Sí, favorece su reparación en vez de su reemplazo.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Vender productos usados en plataformas de segunda mano contribuye a la economía circular?', N'Sí, extiende la vida útil de los productos.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Diseñar envases retornables es parte de un modelo de economía circular?', N'Sí, permite reutilizarlos varias veces.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Es sostenible comprar equipos electrónicos que no permiten cambiar la batería?', N'No, dificulta la reparación y acorta su vida útil.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Los bancos de tiempo o intercambio de servicios apoyan un consumo más circular?', N'Sí, promueven compartir recursos y habilidades.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Reutilizar componentes de aparatos viejos para reparar otros es una práctica de economía circular?', N'Sí, aprovecha materiales que aún sirven.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Fomentar el uso de envases retornables en negocios locales reduce residuos?', N'Sí, disminuye la generación de envases de un solo uso.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Reparar antes de reemplazar es uno de los principios básicos de la economía circular?', N'Sí, es uno de sus principios centrales.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Qué es el ''Barómetro de la moda circular'' utilizado por algunas marcas textiles?', N'Una herramienta que mide el nivel de circularidad de las colecciones de ropa.', N'Dificil', 35, 'ACTIVA'),
(4, N'¿Qué es el consumo ''glocal''?', N'Adaptar decisiones de consumo global a criterios y beneficios locales.', N'Dificil', 35, 'ACTIVA'),
(4, N'¿Qué es la etiqueta de huella de carbono en productos de consumo?', N'Una indicación del total de emisiones generadas durante la vida del producto.', N'Dificil', 35, 'ACTIVA'),
(4, N'¿Qué es la economía de la suficiencia frente a la economía de la eficiencia?', N'La suficiencia busca consumir menos en general; la eficiencia busca hacer más con lo mismo.', N'Dificil', 35, 'ACTIVA'),
(4, N'¿Qué es un ''sistema de depósito y retorno'' de envases?', N'Un esquema donde se paga un depósito por el envase que se devuelve al retornarlo.', N'Dificil', 35, 'ACTIVA'),
(4, N'¿Qué es la ''compra pública sostenible''?', N'Cuando instituciones gubernamentales priorizan criterios ambientales al adquirir bienes y servicios.', N'Dificil', 35, 'ACTIVA'),
(5, N'¿Qué es el ''net metering'' o medición neta en energía solar residencial?', N'Un sistema que permite inyectar el excedente de energía solar a la red y compensarlo en la factura.', N'Dificil', 35, 'ACTIVA'),
(5, N'¿Qué es la ''brecha energética'' entre países desarrollados y en desarrollo?', N'La diferencia en el acceso y consumo de energía moderna entre regiones.', N'Dificil', 35, 'ACTIVA'),
(5, N'¿Qué es la eficiencia energética en edificaciones mediante certificación LEED?', N'Un sistema de certificación internacional que evalúa la sostenibilidad y eficiencia de edificaciones.', N'Dificil', 35, 'ACTIVA'),
(5, N'¿Qué es el ''peak shaving'' en gestión energética?', N'Reducir el consumo eléctrico durante los picos de demanda para aliviar la red.', N'Dificil', 35, 'ACTIVA'),
(5, N'¿Qué es la energía mareomotriz?', N'Energía renovable generada a partir del movimiento de las mareas.', N'Dificil', 35, 'ACTIVA'),
(5, N'¿Qué es un sistema de climatización geotérmica residencial?', N'Un sistema que aprovecha la temperatura estable del subsuelo para climatizar viviendas eficientemente.', N'Dificil', 35, 'ACTIVA'),
(6, N'¿Qué es el ''Food Miles'' o millas alimentarias?', N'La distancia que recorre un alimento desde su producción hasta el consumidor.', N'Dificil', 35, 'ACTIVA'),
(6, N'¿Qué es la acuicultura sostenible?', N'La cría de especies acuáticas bajo prácticas que minimizan el impacto ambiental.', N'Dificil', 35, 'ACTIVA'),
(6, N'¿Qué es la dieta baja en huella de carbono conocida como ''climatarian''?', N'Un patrón alimentario que prioriza alimentos con menor impacto en el cambio climático.', N'Dificil', 35, 'ACTIVA'),
(6, N'¿Qué es el desperdicio alimentario ''de campo'' o pérdida poscosecha?', N'Alimentos perdidos entre la cosecha y la llegada al mercado, antes de llegar al consumidor.', N'Dificil', 35, 'ACTIVA'),
(6, N'¿Qué es la certificación de pesca sostenible MSC?', N'Un sello internacional que certifica que un producto pesquero proviene de una pesquería bien gestionada.', N'Dificil', 35, 'ACTIVA'),
(6, N'¿Qué es el ''nexo agua-energía-alimentos''?', N'El enfoque que analiza la interdependencia entre estos tres recursos en la sostenibilidad.', N'Dificil', 35, 'ACTIVA'),
(7, N'¿Qué es un ''ecoparque industrial'' en el marco de la economía circular?', N'Un parque donde varias industrias comparten e intercambian residuos y recursos entre sí.', N'Dificil', 35, 'ACTIVA'),
(7, N'¿Qué es la ''huella de materiales per cápita'' de un país?', N'La cantidad de materias primas consumidas en promedio por cada habitante.', N'Dificil', 35, 'ACTIVA'),
(7, N'¿Qué es el modelo de ''triple resultado'' (triple bottom line) en sostenibilidad empresarial?', N'Evaluar el desempeño de una empresa en lo económico, social y ambiental.', N'Dificil', 35, 'ACTIVA'),
(7, N'¿Qué es un certificado de reciclabilidad de un producto?', N'Una indicación de qué proporción del producto puede recuperarse y reciclarse al final de su vida útil.', N'Dificil', 35, 'ACTIVA'),
(7, N'¿Qué es la ''minería urbana''?', N'La recuperación de metales y materiales valiosos a partir de residuos electrónicos y urbanos.', N'Dificil', 35, 'ACTIVA'),
(7, N'¿Qué es el índice de circularidad material de una empresa?', N'Una métrica que evalúa qué proporción de los materiales que usa una empresa provienen de fuentes recicladas o reutilizadas.', N'Dificil', 35, 'ACTIVA'),
(3, N'¿Qué es la conectividad funcional entre parches de bosque en un paisaje fragmentado?', N'La capacidad real de las especies de moverse entre esos parches, más allá de la distancia física.', N'Dificil', 35, 'ACTIVA'),
(3, N'¿Qué es un plan de manejo forestal sostenible?', N'Un conjunto de estrategias para aprovechar recursos forestales sin comprometer su renovación futura.', N'Dificil', 35, 'ACTIVA'),
(2, N'¿Qué es el índice de accesibilidad urbana sin auto?', N'Una medida de qué tan fácil es llegar a servicios esenciales sin usar vehículo motorizado propio.', N'Dificil', 35, 'ACTIVA'),
(2, N'¿Qué es la ''internalización de externalidades'' aplicada al transporte contaminante?', N'Incluir en el costo del transporte el daño ambiental que genera, por ejemplo mediante impuestos.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué es la tasa de recuperación de materiales de un sistema de reciclaje?', N'El porcentaje de materiales reciclables que efectivamente se recuperan y procesan.', N'Dificil', 35, 'ACTIVA'),
(1, N'¿Qué es un ecoembalaje?', N'Un empaque diseñado para minimizar su impacto ambiental, priorizando materiales reciclables o biodegradables.', N'Dificil', 35, 'ACTIVA'),
(4, N'¿Qué es un producto de ''segunda vida'' en el mercado de reventa?', N'Un producto usado que se revende para seguir siendo utilizado en vez de desecharse.', N'Intermedia', 20, 'ACTIVA'),
(4, N'¿Qué beneficio tiene comprar electrodomésticos con clasificación energética alta?', N'Consumen menos energía y generan menor gasto a largo plazo.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Qué beneficio tiene usar bombillas inteligentes programables?', N'Permiten optimizar el uso de luz según necesidad, ahorrando energía.', N'Intermedia', 20, 'ACTIVA'),
(5, N'¿Qué es la auditoría energética de un hogar o empresa?', N'Una evaluación del consumo energético para identificar oportunidades de ahorro.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Qué beneficio ambiental tiene reducir el consumo de productos ultraprocesados?', N'Suelen generar menos residuos de empaque y requerir menos procesamiento industrial.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Qué es un mercado agroecológico?', N'Un espacio de venta directa de productos cultivados con prácticas sostenibles.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Qué es la ''trazabilidad de materiales'' en productos reparables?', N'El seguimiento del origen y composición de materiales para facilitar su reparación o reciclaje.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Qué beneficio tiene diseñar productos modulares?', N'Permiten reemplazar solo la pieza dañada en vez de todo el producto.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Qué es un ''centro de reacondicionamiento'' de productos electrónicos?', N'Un lugar donde se revisan, reparan y actualizan equipos usados para volver a venderlos.', N'Intermedia', 20, 'ACTIVA'),
(6, N'¿Qué es el ''etiquetado de frescura dinámico'' en alimentos?', N'Un sistema que indica en tiempo real el estado de frescura de un alimento perecedero.', N'Dificil', 35, 'ACTIVA'),
(5, N'¿Qué es la ''flexibilidad de la demanda eléctrica'' en hogares inteligentes?', N'La capacidad de ajustar el consumo eléctrico doméstico según el precio o disponibilidad de energía.', N'Dificil', 35, 'ACTIVA'),
(4, N'¿Qué es el ''índice de reparabilidad'' de un producto?', N'Una puntuación que indica qué tan fácil es reparar un producto electrónico.', N'Intermedia', 20, 'ACTIVA'),
(3, N'¿Qué es un vivero forestal comunitario?', N'Un espacio donde se producen plántulas de árboles nativos para proyectos de reforestación.', N'Intermedia', 20, 'ACTIVA'),
(2, N'¿Qué es un plan de movilidad urbana sostenible (PMUS)?', N'Un instrumento de planificación que busca reducir el uso del auto y fomentar transporte limpio.', N'Intermedia', 20, 'ACTIVA'),
(1, N'¿Qué es un ecopunto o campana de reciclaje comunitaria?', N'Un contenedor comunitario destinado a la recolección selectiva de materiales reciclables.', N'Facil', 10, 'ACTIVA'),
(1, N'¿El reciclaje de un producto siempre es mejor opción que reducir su consumo desde el inicio?', N'No, reducir el consumo suele ser preferible antes que reciclar.', N'Intermedia', 20, 'ACTIVA'),
(7, N'¿Qué es la ''garantía extendida'' como incentivo a la reparación?', N'Un beneficio que cubre reparaciones por más tiempo, desincentivando el descarte temprano.', N'Facil', 10, 'ACTIVA'),
(6, N'¿Qué es una cadena de frío sostenible en la distribución de alimentos?', N'Un sistema de transporte y almacenamiento refrigerado optimizado para reducir pérdidas y consumo energético.', N'Dificil', 35, 'ACTIVA');
GO